# Generated by Django 5.2.6 on 2025-09-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='api.productplan'),
        ),
    ]
