# Generated by Django 5.2.6 on 2025-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
