# Generated by Django 5.2.6 on 2025-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_watched_ads_usercredits_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplan',
            name='lemon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
