# Generated by Django 5.2.6 on 2025-09-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
    ]
