# Generated by Django 5.2.6 on 2025-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
