# Generated by Django 5.2.6 on 2025-09-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.userplan'),
        ),
    ]
