# Generated by Django 5.2.6 on 2025-09-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_google_id_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='google_id_token',
        ),
    ]
