# Generated by Django 5.2.6 on 2025-09-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_google_id_user_google_id_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id_token',
            new_name='google_id',
        ),
    ]
